#!/bin/bash

clients=$(curl -sS http://clients.easyscreen.io/api/clients| jq -r '[.data[].name] | @csv' |  sed 's/\,/!/g' > /home/kiosk/clients-available.txt)
clients2=$(cat clients-available.txt)
TEXTHEADER="Choose your Library"
TEXTTITLE="Library selection"
values=( $(yad --form --center --width=300 --text-align=center --height=100 --align=left --text="$TEXTHEADER" --center --title="$TEXTTITLE" --separator=' ' \
        --button=Skip:1 --button=Apply:0 \
        --field="Client":CB "$clients2"\
            ) )

if [ $? -eq 0 ]; then
    sudo -u kiosk echo "${values[*]}" | sed 's/^.\(.*\).$/\1/' > /home/kiosk/client-name.txt
fi
