#!/bin/bash

## Define user
USER=kiosk
HOMEDIR=/home/${USER}


GTK_THEME=Adwaita

clients=$(curl -sS http://clients.easyscreen.io/api/clients| jq -r '[.data[].name] | @csv' |  sed 's/\,/!/g' > ${HOMEDIR}/clients-available.txt)
clients2=$(cat clients-available.txt)

TEXTHEADER="Choose your Library"

YAD=(
    yad \
        --title=$TITLE --width=350 --height=150 --align=left --center \
        --skip-taskbar --borders=10 --no-escape --always-print-result --splash --text-align=center
)

values=( $("${YAD[@]}" --text="$TEXTHEADER"  \
        --form ---align=left --separator=' ' \
        --button="gtk-cancel:1" --button="gtk-apply:0" \
        --field="Client":CB "$clients2" \
            ) )

if [ $? -eq 0 ]; then
    sudo -u ${USER} echo "${values[*]}" | sed 's/^.\(.*\).$/\1/' > ${HOMEDIR}/client-name.txt
fi
