#!/bin/bash
TEXTHEADER="Schedule a time for Auto - Shutdown/Startup of the screen"
values=( $(yad --form --center --width=300 --text-align=center --height=150 --align=left --text="$TEXTHEADER" --center --title="Time Schedule" --separator=' ' \
        --button=Skip:1 \
        --button=Apply:0 \
        --field="Shutdown":CB \
            '19:00:00!19:30:00!20:00:00!20:30:00!21:00:00!21:30:00!22:00:00!22:30:00!23:00:00!23:30:00!00:00:00!00:30:00!01:00:00!01:30:00!02:00:00' \
        --field="Startup":CB \
            '05:00:00!05:30:00!06:00:00!06:30:00!07:00:00!07:30:00!08:00:00!08:30:00') )

if [ $? -eq 0 ]; then
    echo "${values[0]}" > /home/kiosk/schedule-shutdown.txt
    echo "${values[1]}" > /home/kiosk/schedule-startup.txt
#    sudo -u kiosk wget -q --output-document=/home/kiosk/conf-schedule.sh https://raw.githubusercontent.com/inleadmedia/easyscreen-ubuntu/new-installation/conf-schedule.sh
#    sudo bash /home/kiosk/conf-schedule.sh > /home/kiosk/schedule-log.txt
fi

shutdown=$(cat /home/kiosk/schedule-shutdown.txt)
startup=$(cat /home/kiosk/schedule-startup.txt)

echo "$TIMESTAMP # Scheduled Suspend and Resume"
sudo touch /etc/systemd/system/auto-suspend.timer
cat <<EOF>> /etc/systemd/system/auto-suspend.timer
[Unit]
Description=Automatically suspend on a schedule
[Timer]
OnCalendar=*-*-* $shutdown
[Install]
WantedBy=timers.target
EOF

sudo touch /etc/systemd/system/auto-suspend.service
cat <<EOF>> /etc/systemd/system/auto-suspend.service
[Unit]
Description=Suspend
[Service]
Type=oneshot
ExecStart=/bin/systemctl suspend
EOF

sudo touch /etc/systemd/system/auto-resume.timer
cat <<EOF>> /etc/systemd/system/auto-resume.timer
[Unit]
Description=Automatically resume on a schedule

[Timer]
OnCalendar=*-*-* $startup
WakeSystem=true
[Install]
WantedBy=timers.target
EOF

sudo touch /etc/systemd/system/auto-resume.service
cat <<EOF>> /etc/systemd/system/auto-resume.service
[Unit]
Description=Does nothing
[Service]
Type=oneshot
ExecStartPre=/bin/bash -c '/bin/true && /bin/sleep 60'
ExecStart=/bin/bash -c '/bin/systemctl reboot'
EOF

sudo systemctl enable auto-suspend.timer
sudo systemctl start auto-suspend.timer

sudo systemctl enable auto-resume.timer
sudo systemctl start auto-resume.timer