#!/bin/bash

GTK_THEME=Adwaita

clients=$(cat /home/kiosk/client-name.txt)

screens=$(curl -sS http://clients.easyscreen.io/api/clients | jq --arg clients "$clients" '.data[] | select (.name==$clients) | .screens | keys |@tsv' | tr -d '",' | sed 's/\\t/!/g' > screen-names.txt && echo "$(<screen-names.txt)")
screens_tmp=$(curl -sS http://clients.easyscreen.io/api/clients | jq --arg clients "$clients" '.data[] | select (.name ==$clients) | .screens' | tr -d '",' > /home/kiosk/screens-available.txt)

YAD=(
    yad \
        --title=$TITLE --width=350 --height=150 --align=left --center \
        --skip-taskbar --borders=10 --no-escape --always-print-result --splash --text-align=center
)

TEXTHEADER="Choose your Screen"

values=( $("${YAD[@]}" --text="$TEXTHEADER" \
        --form ---align=left --separator='!' \
        --button="gtk-cancel:1" --button="gtk-apply:0" \
        --field="Screen":CB "${screens[@]}"\
            ) )

if [ $? -eq 0 ]; then
    sudo -u kiosk echo "${values[@]}" | sed 's/.$//' > /home/kiosk/screen-name.txt
fi

url=$(cat /home/kiosk/screen-name.txt)
cat /home/kiosk/screens-available.txt | grep "${url}" | sed 's/^[^=:]*[=:]//' | awk '{print $1$2,$3,$4,$5,$6,$7}' > /home/kiosk/screen-url.txt
exit
